apiVersion: apps/v1
kind: Deployment
metadata:
  name: demok8s-deployment
  labels:
    app: demok8s
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demok8s
    spec:
      containers:
      - name: demok8s-container
        image: movinvinusandha/testk8s:v2.0.0
        ports:
        - containerPort: 5173
  selector:
    matchLabels:
      app: demok8s
