apiVersion: apps/v1
kind: Deployment
metadata:
  name: demok8s-deployment
  labels:
    app: demok8s
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demok8s
    spec:
      containers:
      - name: demok8s-container
        image: movinvinusandha/testk8s:v4.0.0
        ports:
        - containerPort: 5173
        envFrom:
          - configMapRef:
              name: demok8s-configmap
          - secretRef:
              name: demok8s-secret
        volumeMounts:
          - name: k8s-data-volume
            mountPath: /app/data
      volumes:
      - name: k8s-data-volume
        persistentVolumeClaim:
          claimName: k8s-persistent-volume-claim
  selector:
    matchLabels:
      app: demok8s
