apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/minikube-storage"
  persistentVolumeReclaimPolicy: Delete


